spring:
  profiles:
    include: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bboule/dnyaccts.git"
          username: "bboule"
          password: "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"
encrypt:
  key: "Q7udUkHPuA3VnNlOtksSgQ"
