spring:
  profiles:
    include: "git"
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/bboule/gitops-accounts-sample.git"
          username: "bboule"
          password: "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"
encrypt:
  key: "Q7udUkHPuA3VnNlOtksSgQ"
